//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace PartyCalculator.PartyWebServices {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://partycalculator.abhinav/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://partycalculator.abhinav/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://partycalculator.abhinav/", ConfigurationName="PartyWebServices.PartyCalculatorService")]
    public interface PartyCalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/clearRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/clearResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task clearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/startWorkflowRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/startWorkflowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PartyCalculator.PartyWebServices.Exception), Action="http://partycalculator.abhinav/PartyCalculatorService/startWorkflow/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.startWorkflowResponse> startWorkflowAsync(PartyCalculator.PartyWebServices.startWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/endWorkflowRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/endWorkflowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.endWorkflowResponse> endWorkflowAsync(PartyCalculator.PartyWebServices.endWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/getAllExpensesRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/getAllExpensesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getAllExpensesResponse> getAllExpensesAsync(PartyCalculator.PartyWebServices.getAllExpensesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/getWorkflowsRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/getWorkflowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getWorkflowsResponse> getWorkflowsAsync(PartyCalculator.PartyWebServices.getWorkflowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/addUserToWorkflowRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/addUserToWorkflowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addUserToWorkflowResponse> addUserToWorkflowAsync(PartyCalculator.PartyWebServices.addUserToWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/generateWorkflowIdRequest", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/generateWorkflowIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.generateWorkflowIdResponse> generateWorkflowIdAsync(PartyCalculator.PartyWebServices.generateWorkflowIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://partycalculator.abhinav/PartyCalculatorService/addExpenseToWorkflowRequest" +
            "", ReplyAction="http://partycalculator.abhinav/PartyCalculatorService/addExpenseToWorkflowRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(PartyCalculator.PartyWebServices.Exception), Action="http://partycalculator.abhinav/PartyCalculatorService/addExpenseToWorkflow/Fault/" +
            "Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addExpenseToWorkflowResponse> addExpenseToWorkflowAsync(PartyCalculator.PartyWebServices.addExpenseToWorkflowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWorkflow", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class startWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflowid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyCalculator.PartyWebServices.user user;
        
        public startWorkflowRequest() {
        }
        
        public startWorkflowRequest(int workflowid, PartyCalculator.PartyWebServices.user user) {
            this.workflowid = workflowid;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWorkflowResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class startWorkflowResponse {
        
        public startWorkflowResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endWorkflow", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class endWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflowid;
        
        public endWorkflowRequest() {
        }
        
        public endWorkflowRequest(int workflowid) {
            this.workflowid = workflowid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endWorkflowResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class endWorkflowResponse {
        
        public endWorkflowResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://partycalculator.abhinav/")]
    public partial class expense : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountField;
        
        private bool amountFieldSpecified;
        
        private string descriptionField;
        
        private string expenseTypeField;
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string expenseType {
            get {
                return this.expenseTypeField;
            }
            set {
                this.expenseTypeField = value;
                this.RaisePropertyChanged("expenseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllExpenses", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class getAllExpensesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflowid;
        
        public getAllExpensesRequest() {
        }
        
        public getAllExpensesRequest(int workflowid) {
            this.workflowid = workflowid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllExpensesResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class getAllExpensesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyCalculator.PartyWebServices.expense[] @return;
        
        public getAllExpensesResponse() {
        }
        
        public getAllExpensesResponse(PartyCalculator.PartyWebServices.expense[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://partycalculator.abhinav/")]
    public partial class workflow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private expense[] expensesField;
        
        private user ownerField;
        
        private user[] participantsField;
        
        private int workflowIdField;
        
        private bool workflowIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expenses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public expense[] expenses {
            get {
                return this.expensesField;
            }
            set {
                this.expensesField = value;
                this.RaisePropertyChanged("expenses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public user owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participants", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public user[] participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
                this.RaisePropertyChanged("participants");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int workflowId {
            get {
                return this.workflowIdField;
            }
            set {
                this.workflowIdField = value;
                this.RaisePropertyChanged("workflowId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool workflowIdSpecified {
            get {
                return this.workflowIdFieldSpecified;
            }
            set {
                this.workflowIdFieldSpecified = value;
                this.RaisePropertyChanged("workflowIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWorkflows", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class getWorkflowsRequest {
        
        public getWorkflowsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWorkflowsResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class getWorkflowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyCalculator.PartyWebServices.workflow[] @return;
        
        public getWorkflowsResponse() {
        }
        
        public getWorkflowsResponse(PartyCalculator.PartyWebServices.workflow[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserToWorkflow", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class addUserToWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyCalculator.PartyWebServices.user user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflowid;
        
        public addUserToWorkflowRequest() {
        }
        
        public addUserToWorkflowRequest(PartyCalculator.PartyWebServices.user user, int workflowid) {
            this.user = user;
            this.workflowid = workflowid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserToWorkflowResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class addUserToWorkflowResponse {
        
        public addUserToWorkflowResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateWorkflowId", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class generateWorkflowIdRequest {
        
        public generateWorkflowIdRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateWorkflowIdResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class generateWorkflowIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public generateWorkflowIdResponse() {
        }
        
        public generateWorkflowIdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addExpenseToWorkflow", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class addExpenseToWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflowid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://partycalculator.abhinav/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyCalculator.PartyWebServices.expense expense;
        
        public addExpenseToWorkflowRequest() {
        }
        
        public addExpenseToWorkflowRequest(int workflowid, PartyCalculator.PartyWebServices.expense expense) {
            this.workflowid = workflowid;
            this.expense = expense;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addExpenseToWorkflowResponse", WrapperNamespace="http://partycalculator.abhinav/", IsWrapped=true)]
    public partial class addExpenseToWorkflowResponse {
        
        public addExpenseToWorkflowResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartyCalculatorServiceChannel : PartyCalculator.PartyWebServices.PartyCalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartyCalculatorServiceClient : System.ServiceModel.ClientBase<PartyCalculator.PartyWebServices.PartyCalculatorService>, PartyCalculator.PartyWebServices.PartyCalculatorService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PartyCalculatorServiceClient() : 
                base(PartyCalculatorServiceClient.GetDefaultBinding(), PartyCalculatorServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.PartyCalculatorServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartyCalculatorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PartyCalculatorServiceClient.GetBindingForEndpoint(endpointConfiguration), PartyCalculatorServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartyCalculatorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PartyCalculatorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartyCalculatorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PartyCalculatorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartyCalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task clearAsync() {
            return base.Channel.clearAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.startWorkflowResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.startWorkflowAsync(PartyCalculator.PartyWebServices.startWorkflowRequest request) {
            return base.Channel.startWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.startWorkflowResponse> startWorkflowAsync(int workflowid, PartyCalculator.PartyWebServices.user user) {
            PartyCalculator.PartyWebServices.startWorkflowRequest inValue = new PartyCalculator.PartyWebServices.startWorkflowRequest();
            inValue.workflowid = workflowid;
            inValue.user = user;
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).startWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.endWorkflowResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.endWorkflowAsync(PartyCalculator.PartyWebServices.endWorkflowRequest request) {
            return base.Channel.endWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.endWorkflowResponse> endWorkflowAsync(int workflowid) {
            PartyCalculator.PartyWebServices.endWorkflowRequest inValue = new PartyCalculator.PartyWebServices.endWorkflowRequest();
            inValue.workflowid = workflowid;
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).endWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getAllExpensesResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.getAllExpensesAsync(PartyCalculator.PartyWebServices.getAllExpensesRequest request) {
            return base.Channel.getAllExpensesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getAllExpensesResponse> getAllExpensesAsync(int workflowid) {
            PartyCalculator.PartyWebServices.getAllExpensesRequest inValue = new PartyCalculator.PartyWebServices.getAllExpensesRequest();
            inValue.workflowid = workflowid;
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).getAllExpensesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getWorkflowsResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.getWorkflowsAsync(PartyCalculator.PartyWebServices.getWorkflowsRequest request) {
            return base.Channel.getWorkflowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.getWorkflowsResponse> getWorkflowsAsync() {
            PartyCalculator.PartyWebServices.getWorkflowsRequest inValue = new PartyCalculator.PartyWebServices.getWorkflowsRequest();
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).getWorkflowsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addUserToWorkflowResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.addUserToWorkflowAsync(PartyCalculator.PartyWebServices.addUserToWorkflowRequest request) {
            return base.Channel.addUserToWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addUserToWorkflowResponse> addUserToWorkflowAsync(PartyCalculator.PartyWebServices.user user, int workflowid) {
            PartyCalculator.PartyWebServices.addUserToWorkflowRequest inValue = new PartyCalculator.PartyWebServices.addUserToWorkflowRequest();
            inValue.user = user;
            inValue.workflowid = workflowid;
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).addUserToWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.generateWorkflowIdResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.generateWorkflowIdAsync(PartyCalculator.PartyWebServices.generateWorkflowIdRequest request) {
            return base.Channel.generateWorkflowIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.generateWorkflowIdResponse> generateWorkflowIdAsync() {
            PartyCalculator.PartyWebServices.generateWorkflowIdRequest inValue = new PartyCalculator.PartyWebServices.generateWorkflowIdRequest();
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).generateWorkflowIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addExpenseToWorkflowResponse> PartyCalculator.PartyWebServices.PartyCalculatorService.addExpenseToWorkflowAsync(PartyCalculator.PartyWebServices.addExpenseToWorkflowRequest request) {
            return base.Channel.addExpenseToWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<PartyCalculator.PartyWebServices.addExpenseToWorkflowResponse> addExpenseToWorkflowAsync(int workflowid, PartyCalculator.PartyWebServices.expense expense) {
            PartyCalculator.PartyWebServices.addExpenseToWorkflowRequest inValue = new PartyCalculator.PartyWebServices.addExpenseToWorkflowRequest();
            inValue.workflowid = workflowid;
            inValue.expense = expense;
            return ((PartyCalculator.PartyWebServices.PartyCalculatorService)(this)).addExpenseToWorkflowAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PartyCalculatorServicePort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PartyCalculatorServicePort)) {
                return new System.ServiceModel.EndpointAddress("http://202.166.71.116:2513/PartyCalculator/PartyCalculatorService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PartyCalculatorServiceClient.GetBindingForEndpoint(EndpointConfiguration.PartyCalculatorServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PartyCalculatorServiceClient.GetEndpointAddress(EndpointConfiguration.PartyCalculatorServicePort);
        }
        
        public enum EndpointConfiguration {
            
            PartyCalculatorServicePort,
        }
    }
}
